### ISSUE TITLE
How to reload or reinitialize?

### ISSUE THREAD

**Issue by samsnori** [lucaong/react-minisearch#45]
When I'm using useMiniSearch(data,opts) how can I reinitialize when the data changes?

**Comment by lucaong** [comment]
Hi @samsnori ,
You have several options. If your data changed completely, or you don’t have a way to know reliably what changed, you can call `removeAll` without arguments (to clear the whole index instantly) and then `addAll` or `addAllAsync` to index the new documents.

Otherwise, if you know which documents changed, you can call `replace` to  replace those documents that changed, `remove` (or `discard`) to remove what should be deleted, or `add` to add new documents.

Those functions are all returned by `useMiniSearch`. I hope this helps.

**Comment by samsnori** [comment]
Thanks so much @lucaong!   I'm using `removeAll()` followed by `addAll()` now.  That's working perfectly.

When I call `removeAll()` followed by `addAllAsync()`, I sometimes get an error like:

```
Error: MiniSearch: duplicate ID f6ce8ef4-7339-42c8-a2fc-6452d986c1a0
    at MiniSearch2.add (react-minisearch.js?v=348b99bc:608:19)
    at MiniSearch2.addAll (react-minisearch.js?v=348b99bc:670:20)
    at react-minisearch.js?v=348b99bc:700:32
```
To me, it makes sense that `removeAll()` checks that there is no `addAllAsync()` in progress internally which is probably causing this error.

**Comment by lucaong** [comment]
Hi @samsnori ,
Yes, I should have added that when using `addAllAsync` one should either await on the promise, or check the `isIndexing`  value to make sure that things don’t step on each other. Using `addAll` is usually simpler and faster, and `addAllAsync` should be preferred only when the collection is large enough to block the main thread during indexing.

Your comment makes me think that it would be useful to have a way to cancel an in progress async indexing, for example when the documents are stale and one wants to clear the whole index. I will work on it soon.

**Comment by lucaong** [comment]
I will close the issue as the main question should be solved. I’ll work on the improvement at some point soon.
